# Custom project creation function, copied as a starting point from
#     https://rstudio.github.io/rstudio-extensions/rstudio_project_templates.html
# Copying functions and replacements originally taken from
#     https://blog.devgenius.io/make-your-own-rstudio-project-template-1f77c4888e79
# and heavily modified

create_LIC_project <- function(path, ...) {
    # ensure path exists
    dir.create(path, recursive = TRUE, showWarnings = FALSE)



    # LIC.src <- function (..., lib.loc = NULL, mustWork = FALSE){
    #     system.file(..., package = "LifeInsuranceContracts", lib.loc = lib.loc, mustWork = mustWork)
    # }
    #
    # from <- LIC.src("templatedemo")
    #
    # fs::dir_copy(
    #     path = from,
    #     new_path = path,
    #     overwrite = TRUE
    # )

    # generate header for file
    header <- c(
        "# This file was generated by a call to 'ptexamples::hello_world()'.",
        "# The following inputs were received:",
        ""
    )

    # collect inputs and paste together as 'Parameter: Value'
    dots <- list(...)
    text <- lapply(seq_along(dots), function(i) {
        key <- names(dots)[[i]]
        val <- dots[[i]]
        paste0(key, ": ", val)
    })

    # collect into single text string
    contents <- paste(
        paste(header, collapse = "\n"),
        paste(text, collapse = "\n"),
        sep = "\n"
    )

    # write to index file
    writeLines(contents, con = file.path(path, "RechnungGesamtbestand.R"))
}
